name: Deploy website
on:
    workflow_dispatch:
    push:
        branches: release

jobs:
    run:
        name: Deploy website
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@main
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.WGYTBOT }}

            - name: Setup Node.JS
              uses: actions/setup-node@main
              with:
                  node-version: 14
                  cache: "npm"

            - name: Install
              run: npm install --force

            - name: Build Tailwind
              run: npm run build:tailwind

            - name: Deploy
              run: npx openode deploy -t ${{ secrets.OPENODE }} -s "auth.onedot.cf"
