name: Deploy website
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    run:
        name: Deploy website
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.0
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.WGYTBOT }}

            - name: Setup Node.JS
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm install --force

            - name: Build Tailwind
              run: npm run build:tailwind

            - name: Configure
              run: npx openode ci-conf "${{ secrets.OPENODE }}" "auth.onedot.cf"

            - name: Deploy
              run: npx openode deploy
