name: Install dependencies
on:
    workflow_dispatch:
    push:
        branches: main
        paths:
            - package.json
            - package-lock.json
    schedule:
        - cron: "0 0 */6 * * "

jobs:
    run:
        name: Install dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@main
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.WGYTBOT }}

            - name: Setup Node.JS
              uses: actions/setup-node@main
              with:
                  node-version: 14
                  cache: "npm"

            - name: Remove
              run: rm package-lock.json --force

            - name: Install
              run: npm install

            - name: Vulnerabilities
              run: npm audit fix

            - name: Unneeded
              run: npm prune

            - name: Duplicates
              run: npm dedupe

            - name: Health
              run: npm dedupe

            - name: Pull
              run: git pull

            - name: Commit
              id: commit
              uses: stefanzweifel/git-auto-commit-action@master
              with:
                  commit_message: "Install dependencies to prevent deduplication"
                  branch: main
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author: wgytbot <83586655+wgytbot@users.noreply.github.com>
