name: Install dependencies
on:
    push:
        branches:
            - main

jobs:
    install:
        name: Install dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Setup Node.JS
              uses: actions/setup-node@main
              with:
                  node-version: 12.22.1

            - name: Install
              run: npm install

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@master
              with:
                  commit_message: "Install dependecies"
                  branch: main
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author: wgytbot <83586655+wgytbot@users.noreply.github.com>
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.WGYTBOT }}
                  event-type: lint
