name: Install dependencies
on:
    workflow_dispatch:
    push:
        branches: main
    schedule:
        - cron: "0 0 */6 * * "

jobs:
    install:
        name: Install dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              if: always()
              uses: actions/checkout@main
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              if: always()
              uses: actions/setup-node@main
              with:
                  node-version: 12.22.1

            - name: Remove
              if: always()
              run: rm package-lock.json

            - name: Install
              if: always()
              run: npm install

            - name: Commit
              if: always()
              uses: stefanzweifel/git-auto-commit-action@master
              with:
                  commit_message: "Install dependencies"
                  branch: main
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author:
                      wgytbot <83586655+wgytbot@users.noreply.github.com>
