name: Labeler
on: pull_request_target

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/labeler@v2
              if: always()
              with:
                  repo-token: "${{ secrets.WGYTBOT }}"
                  sync-labels: true
