name: Labeler
on: [pull_request, pull_request_target]

jobs:
    label:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/labeler@v2
              with:
                  repo-token: "${{ secrets.WGYTBOT }}"
                  sync-labels: true
