name: Run Lighthouse
on:
    workflow_dispatch:
    schedule:
        - cron: "00 00 * * SUN"

jobs:
    run:
        name: Run Lighthouse
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.WGYTBOT }}

            - name: Analyze
              uses: foo-software/lighthouse-check-action@v4.0.0
              id: lighthouse
              with:
                  emulatedFormFactor: all
                  locale: en
                  prCommentEnabled: false
                  verbose: true
                  urls: >-
                      https://auth.onedot.cf,
                      https://auth.onedot.cf/auth?url=https%3A%2F%2Fauth.onedot.cf%2F,
                      https://auth.onedot.cf/auth/email?url=https%3A%2F%2Fauth.onedot.cf%2F,
                      https://auth.onedot.cf/docs/auth

            - name: Setup Node.JS
              if: ${{ !cancelled() }}
              uses: actions/setup-node@v2.4.0
              with:
                  node-version: 14
                  cache: "npm"

            - name: Install
              if: ${{ !cancelled() }}
              run: npm install --force

            - name: Comment
              if: success()
              run:
                  node --trace-warnings --harmony .github/workflows/lighthouse.js '${{
                  secrets.WGYTBOT }}' '${{ join(steps.lighthouse.outputs.*, '\n') }}' ''

            - name: Comment
              if: failure()
              run:
                  node --trace-warnings --harmony .github/workflows/lighthouse.js '${{
                  secrets.WGYTBOT }}' '{}' '1'
