name: Format and lint
on:
    pull_request:
        types: [opened]
    workflow_dispatch:

jobs:
    run:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@main
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.WGYTBOT }}

            - name: Setup Node.JS
              uses: actions/setup-node@main
              with:
                  node-version: 14
                  cache: "npm"

            - name: Install
              run: npm install

            - name: Mustaches
              run: npm run lint:mustaches

            - name: Prettier
              if: ${{ !cancelled() }}
              run: npm run lint:prettier

            - name: ESLint
              if: ${{ !cancelled() }}
              run: npm run lint:eslint

            - name: Typescript
              if: ${{ !cancelled() }}
              run: npm run lint:typescript

            - name: Commit
              if: ${{ !cancelled() }}
              uses: stefanzweifel/git-auto-commit-action@master
              with:
                  commit_message: "Lint and format code"
                  branch: ${{ github.head_ref }}
                  add_options: "--ignore-removal"
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author: wgytbot <83586655+wgytbot@users.noreply.github.com>
