name: Lint
on: [push, pull_request, workflow_dispatch]

jobs:
    run:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.JS
              uses: actions/setup-node@v1
              with:
                  node-version: 12.22.1

            - name: Install
              run: npm install eslint eslint-plugin-html jslint prettier write-good --save-dev

            - name: Prettier
              run: npx prettier --write .

            - name: ESLint
              run: npx eslint --fix .

            - name: JSLint
              run: npx jslint .

            - name: write good
              run: npx write-good --yes-eprime --parse .

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Lint and format code using Prettier and ESLint"
                  branch: main
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author: wgytbot <83586655+wgytbot@users.noreply.github.com>
