name: Mark stale issues and pull requests
on:
    schedule:
        - cron: "30 1 * * *"

jobs:
    run:
        name: Mark as stale
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write

        steps:
            - name: Mark
              if: always()
              uses: actions/stale@v3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: "Stale issue message"
                  stale-pr-message: "Stale pull request message"
                  stale-issue-label: "no-issue-activity"
                  stale-pr-label: "no-pr-activity"
