name: Synchronize with Transifex
on:
    workflow_dispatch:
    schedule:
        - cron: "00 23 * * *"
    push:
        branches: main
        paths:
            - _locales/**.json

jobs:
    sync:
        name: Synchronize
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              if: always()
              uses: actions/checkout@main
              with:
                  ref: ${{github.head_ref}}
                  token: ${{secrets.WGYTBOT}}

            - name: Setup Python
              if: always()
              uses: actions/setup-python@main
              with:
                  python-version: 3.x

            - name: Install
              if: always()
              run: pip install transifex-client

            - name: Setup Transifex
              if: always()
              run:
                  tx init --host='https://www.transifex.com' --user=api
                  --force-save --skipsetup --token=${{secrets.TRANSIFEX}}
                  --no-interactive

            - name: Configure Transifex
              if: always()
              run:
                  tx config mapping --resource=1auth.mainStrings --source
                  --language=en --type=STRUCTURED_JSON --source-language=en
                  --source-file=_locales/en_US.json --execute
                  --expression="_locales/<lang>.json"

            - name: Push
              if: always()
              run: tx push --source --translations --no-interactive

            - name: Pull
              if: always()
              run: tx pull --all --source --no-interactive

            - name: Commit
              if: always()
              uses: stefanzweifel/git-auto-commit-action@master
              with:
                  commit_message: "Synchronize strings with Transifex"
                  branch: main
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author:
                      wgytbot <83586655+wgytbot@users.noreply.github.com>
