name: Synchronize with Transifex
on:
    workflow_dispatch:
    schedule:
        - cron: "00 23 * * *"
    push:
        branches: develop
        paths:
            - _locales/en_US.json

jobs:
    run:
        name: Synchronize
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.5
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.WGYTBOT }}

            - name: Setup Python
              uses: actions/setup-python@v3.1.1
              with:
                  python-version: 3.x

            - name: Install
              run: pip install transifex-client

            - name: Configure
              run:
                  touch .transifexrc; echo "[https://www.transifex.com]" > .transifexrc; echo
                  "api_hostname = https://api.transifex.com" >> .transifexrc; echo "hostname =
                  https://www.transifex.com" >> .transifexrc; echo "password =" "${{
                  secrets.TRANSIFEX }}" >> .transifexrc; echo "username = api" >> .transifexrc;

            - name: Pull
              continue-on-error: true
              run: tx pull --all --skip --no-interactive --force --mode=onlytranslated

            - name: Push
              continue-on-error: true
              run: tx push --source --no-interactive --force --skip

            - name: Commit
              id: commit
              uses: stefanzweifel/git-auto-commit-action@v4.12.0
              with:
                  commit_message: "Synchronize strings with Transifex"
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author: wgytbot <83586655+wgytbot@users.noreply.github.com>
